# fly.toml app configuration file generated for task-bounty on 2023-07-21T21:06:22-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "task-bounty"
primary_region = "iad"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  MONGO_URI="mongodb+srv://domfounds:MZ2Z45ViPREQwaJr@cluster0.ituafe6.mongodb.net/?retryWrites=true&w=majority"
  MONGO_USER="domfounds"
  MONGO_PASSWORD="MZ2Z45ViPREQwaJr"
  JWT_SECRET="iamoverthisproject"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
